import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>

      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.imagewrap}>
          <Image className={styles.myimg} src="/coder.avif" width={140} height={140} />
        </div>
        <h2>&lt;HuntingCoder/&gt;</h2>
        <p className={styles.description}>
          A blog by hunting coder t o hunting coder Lorem ipsum, dolor sit amet consectetur adipisicing elit. Incidunt voluptatum pariatur, magnam dolorum non animi officia autem possimus, sunt corporis ea harum maiores nisi quidem. Dicta, maxime ducimus. Sit, cumque!
        </p>
        <div className="blogs">
          <h2>Popular blogs</h2>
          <div className="blogitem">
            <h3>How to learn js</h3>
            <p>watch some videoes  from youtube and lear javascript</p>
          </div>
          <div className="blogitem">
            <h3>How to learn js</h3>
            <p>watch some videoes  from youtube and lear javascript</p>
          </div>
          <div className="blogitem">
            <h3>How to learn js</h3>
            <p>watch some videoes  from youtube and lear javascript</p>
          </div>
          <div className="blogitem">
            <h3>How to learn js</h3>
            <p>watch some videoes  from youtube and lear javascript</p>
          </div>

        </div>

      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
